app/cf/urls.py
from django.contrib import admin
from django.urls import path, include

# from assets.assets import DashboardView

urlpatterns = [
    # path("", DashboardView.as_view(), name="dashboard"),
    path("admin/", admin.site.urls),
    path("profile/", include("users.urls", namespace="users")),
    path("", include("payments.urls")),
    path("accounts/", include("allauth.urls")),
]

app/users/urls.py
from django.urls import path

from . import views

app_name = "users"


urlpatterns = [
    path(
        "detail/<slug:slug>", views.ProfileDetailView.as_view(), name="profile-detail"
    ),
    path("edit/<slug:slug>", views.ProfileUpdateView.as_view(), name="profile-update"),
]

app/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils.text import slugify
from django.urls import reverse


class User(AbstractUser):
    # is_customer = models.BooleanField(default=True)
    # is_dispatcher = models.BooleanField(default=False)
    # is_team_lead = models.BooleanField(default=False)
    # is_driver = models.BooleanField(default=False)
    pass


class Profile(models.Model):
    """
    User Profile model
    """

    user = models.OneToOneField(User, related_name="profile", on_delete=models.CASCADE)
    slug = models.SlugField(max_length=200, unique=True, null=True, blank=True)
    first_name = models.CharField(max_length=200, blank=True, null=True)
    last_name = models.CharField(max_length=200, blank=True, null=True)
    dob = models.DateField("date of birth", blank=True, null=True)
    gender = models.CharField(max_length=1)
    contact = models.CharField(max_length=15)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.user.username)
        super(Profile, self).save(*args, **kwargs)
    
    def get_absolute_url(self):
        return reverse("users:profile-detail", kwargs={"slug": self.slug})
    

    def get_email(self):
        return self.user.email

    def __str__(self):
        if self.first_name and self.last_name:
            return self.first_name + " " + self.last_name
        return self.user.username

app/users/views.py
from django.shortcuts import render
from django.views.generic import UpdateView, DetailView, ListView
from .models import Profile
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin


class ProfileUpdateView(LoginRequiredMixin, UpdateView):
    model = Profile
    fields = "__all__"
    template_name_suffix = '_update_form'
    


class ProfileDetailView(LoginRequiredMixin, DetailView):
    model = Profile

app/templates/users/profile_detail.html
{% extends 'base.html' %}


{% block head_title %}
{{object}}
{% endblock head_title %}

{% block content %}

<div class="container my-5">
    <div class="row">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header">
                    <h4 class="pt-3">{{object}}</h4>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-6">
                            <!-- <p><strong>Name:</strong> {{object}}</p> -->
                            <p><strong>Email:</strong> {{object.get_email}} <a href="{% url 'account_email' %}">change email</a></p>
                            <p><strong>Phone:</strong> {{object.contact}}</p>
                            <p><strong>Gender:</strong> {{object.gender}}</p>
                            <p><strong>DOB:</strong> {{object.dob}}</p>
                        </div>
                        <!-- <div class="col-md-6">
                                <p><strong>Company:</strong> {{user.company}}</p>
                                <p><strong>Website:</strong> {{user.website}}</p>
                                <p><strong>Twitter:</strong> {{user.twitter}}</p>
                                <p><strong>Facebook:</strong> {{user.facebook}}</p>
                                <p><strong>Linkedin:</strong> {{user.linkedin}}</p>
                                <p><strong>Github:</strong> {{user.github}}</p>
                            </div> -->
                    </div>
                </div>
                <div class="card-footer p-3 px-5 text-end">
                    <a title="edit profile information" class="text-decoration-none fs-5"
                        href="{% url 'users:profile-update' request.user.profile.slug%}">Edit</a>
                </div>
            </div>
        </div>
    </div>

    {% endblock content %}

app/templates/users/profile_update_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block head_title %}
{{object}}
{% endblock head_title %}

{% block content %}

<div class="container my-5">
    <div class="row">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header">
                    <h4 class="pt-3">{{object}}</h4>
                </div>
                <div class="card-body">
                        <div class="col-md-6 mx-auto">
                            <form action="" method="post">
                                {% csrf_token %}
                                {{form|crispy}}
                                <div class="form-group my-3 text-end">
                                    <button type="submit" class="btn btn-sm px-5 btn-outline-dark">Update</button>
                                </div>
                            </form>
                        </div>
                        <!-- <div class="col-md-6">
                                <p><strong>Company:</strong> {{user.company}}</p>
                                <p><strong>Website:</strong> {{user.website}}</p>
                                <p><strong>Twitter:</strong> {{user.twitter}}</p>
                                <p><strong>Facebook:</strong> {{user.facebook}}</p>
                                <p><strong>Linkedin:</strong> {{user.linkedin}}</p>
                                <p><strong>Github:</strong> {{user.github}}</p>
                            </div> -->
                    </div>
             
            </div>
        </div>
    </div>

    {% endblock content %}