app/cf/urls.py
from django.contrib import admin
from django.urls import path, include

# from assets.assets import DashboardView

urlpatterns = [
    # path("", DashboardView.as_view(), name="dashboard"),
    path("admin/", admin.site.urls),
    path("profile/", include("users.urls", namespace="users")),
    path("", include("payments.urls")),
    path("accounts/", include("allauth.urls")),
]

app/users/urls.py
from django.urls import path

from . import views

app_name = "users"


urlpatterns = [
    path(
        "detail/<slug:slug>", views.ProfileDetailView.as_view(), name="profile-detail"
    ),
    path("edit/<slug:slug>", views.ProfileUpdateView.as_view(), name="profile-update"),
]

app/templates/base.html
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport"
        content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link
        href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
        rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
        crossorigin="anonymous">
    <link rel="stylesheet"
        href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.1/font/bootstrap-icons.css">
    <link rel="preconnect"
        href="https://fonts.googleapis.com">
    <link rel="preconnect"
        href="https://fonts.gstatic.com"
        crossorigin>
    <link
        href="https://fonts.googleapis.com/css2?family=Montserrat&display=swap"
        rel="stylesheet">
    <style>
        html,
        body {
            font-family: 'Montserrat', sans-serif;
        }

        .b-example-divider {
            height: 3rem;
            background-color: rgba(0, 0, 0, .1);
            border: solid rgba(0, 0, 0, .15);
            border-width: 1px 0;
            box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
        }

        .form-control-dark {
            color: #fff;
            background-color: var(--bs-dark);
            border-color: var(--bs-gray);
        }

        .form-control-dark:focus {
            color: #fff;
            background-color: var(--bs-dark);
            border-color: #fff;
            box-shadow: 0 0 0 .25rem rgba(255, 255, 255, .25);
        }

        .bi {
            vertical-align: -.125em;
            fill: currentColor;
        }

        .text-small {
            font-size: 85%;
        }

        .dropdown-toggle {
            outline: 0;
        }
        .messages {
            position: absolute; 
            left: 5rem; 
            bottom: 2rem;
            z-index:1;
            -webkit-animation: cssAnimation 5s forwards; 
            animation: cssAnimation 5s forwards; 
        }
        @keyframes cssAnimation {
            0%   {opacity: 1;}
            90%  {opacity: 1;}
            100% {opacity: 0;}
        }
        @-webkit-keyframes cssAnimation {
            0%   {opacity: 1;}
            90%  {opacity: 1;}
            100% {opacity: 0;}
        }

    </style>

    <title>

        {% block head_title %}

        {% endblock head_title %}
        NCA
    </title>
</head>

<body>

    {% include 'navbar.html' %}
    {% include 'messages.html' %}
    <div class="min-vh-100">
        {% block content %}

        {% endblock content %}
    </div>
    {% include 'footer.html' %}


    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script
        src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
</body>

</html>

app/templates/dashboard.html
{% extends 'base.html' %}

{% block head_title %}
Dashboard
{% endblock head_title %}

{% block content %}
<div class="container my-5">
    <h1>Dashboard</h1>
    <hr>
    <br>

    <div class="mx-auto ">
        <div class="row">
            <div class="col-lg-3">
                <div class="my-3">
                    <a class="text-dark fw-bolder"
                        href="{% url 'payments:payment-create' %}">Add a
                        payment</a>
                </div>
            </div>
            <div class="col">
                <div class="table-responsive">
                    <table class="table table-hover">
                        <thead>
                            <tr>
                                <th scope="col">Year</th>
                                <th scope="col">Income</th>
                            </tr>
                        </thead>
                        <tbody>


                            {% for object in object_list %}
                            <tr>
                                <td>{{object.year}}</td>
                                <td>XCD${{object.payment_years.all.get_year_total_payments}}</td>
                                </td>
                            </tr>
                            {% empty %}
                            <tr>
                                <td class="text-center"
                                    colspan="4">No data</td>
                            </tr>
                            {% endfor %}

                            {{client_payment}}

                        </tbody>
                    </table>
                </div>
            </div>
        </div>

    </div>

</div>
{% endblock content %}

app/templates/footer.html
<footer class="footer mt-auto py-3 bg-light">
    <div class="container">
        <span class="text-muted">Place sticky footer content here.</span>
    </div>
</footer>

app/templates/messages.html
{% if messages %}
{% for message in messages %}
<div
    class="messages col-lg-3 alert alert-info alert-dismissible fade show text-center"
    role="alert">
    <strong>{{message}}</strong>
    <button type="button"
        class="btn-close"
        data-bs-dismiss="alert"
        aria-label="Close"></button>
</div>
{% endfor %}
{% endif %}

app/templates/navbar.html
{% if request.user.is_authenticated %}

<div class="container">
    <header
        class="d-flex flex-wrap align-items-center justify-content-center justify-content-md-between py-3 mb-4 border-bottom">
        <a href="/"
            class="d-flex align-items-center col-md-3 mb-2 mb-md-0 text-dark text-decoration-none">
            <h1 class="display-4">
                NCA
            </h1>
        </a>

        <ul class="nav col-12 col-md-auto mb-2 justify-content-center mb-md-0">
            <li><a href="{% url 'license-payment-list' %}"
                    class="nav-link px-2 link-dark">Payments</a></li>
            <li><a href="{% url 'client-list' %}"
                    class="nav-link px-2 link-dark">Clients</a></li>

            <li><a href="{% url 'license-list' %}"
                    class="nav-link px-2 link-dark">Licenses</a></li>
            <li><a href="{% url 'issued-license-list' %}"
                    class="nav-link px-2 link-dark">Issued licenses</a></li>
        </ul>

        <div class="col-md-3 text-end">

            <a title="your profile"
                href="{% url 'users:profile-detail' request.user.profile.slug %}"
                type="button"
                class="text-decoration-none text-dark me-3">
                <i class="bi bi-person-badge fs-4"></i>
            </a>
            <a href="{% url 'account_logout' %}"
                type="button"
                class="text-decoration-none text-dark">
                <i title="logout"
                    class="bi bi-door-open-fill fs-4"></i>
            </a>

            <!-- <a href="{% url 'account_login' %}"
                type="button"
                class="btn btn-outline-success me-2">login</a>
            <a href="{% url 'account_signup' %}"
                type="button"
                class="btn btn-success">Sign-up</a> -->
            {% endif %}
        </div>
    </header>
</div>

app/templates/pagination.html
<div class="container text-center">
<div class="my-3">
    <span class="step-links">
        {% if page_obj.has_previous %}
        <a href="?page=1">&laquo; first</a>
        <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}">next</a>
        <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>
</div>